export  const AdsFields = [
  { 
    key: "id", 
    label: "Id", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Id",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    options: null,
    form_show: true
  },
  { 
    key: "user_id", 
    label: "User Id", 
    type: "select", 
    cell_type: "relation",
    display_field: "user.name",
    required: 0, 
    placeholder: "Enter User Id",
    searchable: false,
    filterable: true,
    sortable: true,
    table_show: false,
    options: { label: "name", value: "id" },
        endpoint: 'users',
    relation_fields: 'id,name', 

    
  },
  { 
    key: "category_id", 
    label: "Category Id", 
    type: "select", 
    cell_type: "relation",
    display_field: "category.name",
    required: 0, 
    placeholder: "Enter Category Id",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
     form_show: true,
    endpoint: 'categories',
    relation_fields: 'id,name', 
    options: { label: 'name', value: 'id' }

  },
  { 
    key: "status", 
    label: "Status", 
    type: "select", 
    cell_type: "badge",
    display_field: null,
    required: 1, 
    placeholder: "Enter Status",
    searchable: false,
    filterable: true,
    sortable: true,
    table_show: true,
    form_show: true,   
    options: [{ label: "Pending", value: 'pending' }, { label: "Confirmed", value: 'confirmed' }, { label: "Canceled", value: 'canceled' }, { label: "Expired", value: 'expired' }]
  },
  { 
    key: "title", 
    label: "Title", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Title",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    options: null
  },
  { 
    key: "title_ar", 
    label: "Title Ar", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Title Ar",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    options: null
  },
  { 
    key: "description", 
    label: "Description", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 0, 
    placeholder: "Enter Description",
    searchable: true,
    filterable: false,
    sortable: false,
    table_show: false,
    options: null
  },
  { 
    key: "image", 
    label: "Image", 
    type: "file", 
    cell_type: "image",
    display_field: null,
    required: 1, 
    placeholder: "Enter Image",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    options: null
  },
  { 
    key: "attachment_file", 
    label: "Attachment File", 
    type: "file", 
    cell_type: "image",
    display_field: null,
    required: 0, 
    placeholder: "Enter Attachment File",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    options: null
  },
  { 
    key: "price", 
    label: "Price", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Price",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    options: null
  },
  { 
    key: "active", 
    label: "Active", 
    type: "checkbox", 
    cell_type: "badge",
    display_field: null,
    required: 1, 
    placeholder: "Enter Active",
    searchable: false,
    filterable: true,
    sortable: true,
    table_show: true,
    options: [{ label: 'Active', value: 1, color: 'success' }, { label: 'Inactive', value: 0, color: 'danger' }]
  },
  { 
    key: "is_featured", 
    label: "Is Featured", 
    type: "checkbox", 
    cell_type: "badge",
    display_field: null,
    required: 1, 
    placeholder: "Enter Is Featured",
    searchable: false,
    filterable: true,
    sortable: true,
    table_show: false,
    options: [{ label: 'Active', value: 1, color: 'success' }, { label: 'Inactive', value: 0, color: 'danger' }]
  },
  { 
    key: "published_at", 
    label: "Published At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Published At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    options: null
  },
  { 
    key: "expire_date", 
    label: "Expire Date", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Expire Date",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    options: null
  },
  { 
    key: "created_at", 
    label: "Created At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Created At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    options: null
  },
  { 
    key: "updated_at", 
    label: "Updated At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Updated At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    options: null
  }
];
